@extends('layouts.app')

@section('content')

    
  <!--Page Title-->
    <section style="padding: 179px 0px 90px;background-image:url({{asset('assets/images/background/8.jpg')}} )" class="page-title">
      <div class="auto-container">
      <div class="content">
        <h1>Disclaimer</h1>
        <ul class="page-breadcrumb">
          <li><a href="./">Home</a></li>
          <li>Pages</li>
          <li>Disclaimer</li>
        </ul>
      </div>
        </div>
    </section>
    <!--End Page Title-->
  
 <section class="about-section">
    <div class="auto-container">
      <div class="row clearfix">
        
        <!-- Content Column -->
        <div class="content-column col-lg-12 col-md-12 col-sm-12">
          <div class="inner-column">
            
            <!-- Sec Title -->
            <div class="sec-title">
              <div class="title">DISCLAIMER</div>
              
            </div>
            
           
            <div class="row clearfix">
              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                <!--   <li><strong>In- house students Guidance. </strong> </li> -->
<p>  
This document is an electronic record in terms of Information Technology Act, 2000 ("Act") and made thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology (Amendment) Act, 2008. This electronic record is generated by a computer system and does not require any physical or digital signatures.
</p>
<p>  
This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and terms and conditions for access and/or usage of website. Here website means www.brainmovers.in
</p>
<p>  
Brain Movers endeavours to provide the utmost quality of the services rendered and shall make every effort to keep the site and its contents correct and up to date. However, we do not vouch for, or guarantee the accuracy, reliability, adequacy, or completeness of any data or content and we shall not be liable for any errors, omissions or other defects, delays or interruptions in such data, or for any actions taken in reliance thereon.
</p>
<p>  
Brain Movers shall not be responsible in any manner for any liability that may arise directly or indirectly due to use of information, content or the report, including (but not limited to) errors or omissions, the accuracy, completeness, reliability, or reasonableness of factual or scientific assumptions, studies, remarks, test results or conclusions contained in such information, content or report.
</p>
<p>  
Brain Movers provides advice and recommendations based on the information received from the user/s and results of the psychometric assessments, and is not responsible for the outcome of the assessments in any manner.
</p>
<p>  
Brain Movers will not be liable to you in relation to the contents of, or use of, or otherwise in connection with, this website, for any direct, indirect, incidental, special, consequential or for any business losses, loss of revenue, profits , loss of contracts or business relationships, loss  of goodwill, or loss or corruption of information or data or other intangible losses arising out of or in connection with the website and its services.
</p>
<p>  
Brain Movers shall not be responsible in any manner for any liability that may arise directly or indirectly due to use of information, content or the report, including (but not limited to) errors or omissions, the accuracy, completeness, reliability, or reasonableness of factual or scientific assumptions, studies, remarks, test results or conclusions contained in such information, content or report.
</p>
<p>The information/results provided by the website is only for bonafide guidance and general information purposes and does not constitute any commitment of performance of user in any manner and shall not be relied upon as the sole factor for the purposes of your decision making, admission or such ancillary purpose as other relevant factors including but not limited to educational qualification, Intellect, or other relevant factors play an important role for the said purpose.</p>
<p>Brain Movers is not responsible for any act of the career expert and counselors beyond the scope of the services rendered by it in any manner.</p>
<p>Brain Movers provides advice and recommendations based on the information received from the user/s and results of the psychometric assessments, and is not responsible for the outcome of the assessments in any manner.</p>
                </ul>
              </div>
           
     
              
            </div>
            
             
          </div>
        </div>
        
    
        
      </div>
    </div>
   </section>
    <!--End Page Title-->
  
  <!-- Case Section Three-->
   
  <!-- End Case Section Three-->
  
  <!-- Call To Action Two -->
  <section class="call-to-action-two">
    <div class="auto-container">
      <div class="clearfix">
        
        <div class="pull-left">
          <h2>Request for <span>Guidance</span></h2>
        </div>
        <div class="pull-right">
          <a href="{{URL('contact')}}" class="theme-btn btn-style-five">Request now <span class="icon fa fa-arrow-right"></span></a>
        </div>
        
      </div>
    </div>
  </section>
  <!-- End Feature Section -->
@endsection
