@extends('layouts.app')

@section('content')

    
  <!--Page Title-->
    <section style="padding: 179px 0px 90px;background-image:url({{asset('assets/images/background/8.jpg')}} )" class="page-title" >
      <div class="auto-container">
      <div class="content">
        <h1>Privacy<span>Policy</span></h1>
        <ul class="page-breadcrumb">
          <li><a href="./">Home</a></li>
          <li>Pages</li>
          <li>Privacy Policy</li>
        </ul>
      </div>
        </div>
    </section>
    <!--End Page Title-->
  
 <section class="about-section">
    <div class="auto-container">
      <div class="row clearfix">
        
        <!-- Content Column -->
        <div class="content-column col-lg-12 col-md-12 col-sm-12">
          <div class="inner-column">
            
            <!-- Sec Title -->
            <div class="sec-title">
              <div class="title">PRIVACY POLICY</div>
              
            </div>
            
           
            <div class="row clearfix">
              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>Introduction </strong> </li>
                    <p>  
                    When you use www.brainmovers.in, you trust us with your information. We are committed to keeping that trust. That starts with helping you understand our privacy practices. This Privacy Policy is meant to help you understand what data we collect, why we collect it, and what we do with it. This is important; we hope you will take time to read it carefully.
                    </p>
                    <p>  
                    This document is an electronic record in terms of Information Technology Act, 2000 ("Act") and made there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology (Amendment) Act, 2008. This user agreement is generated by a computer system and does not require any physical or digital signatures.
                    </p>
                    <p>  
                    This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and terms and conditions for access and/or usage of www.lcat.in ("Website").
                    </p>
                </ul>
              </div>
           <div><h2> <span>Personal information gathered by BrainMovers</span></h2></div>
              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>Your Information  </strong> </li>
                    <p>  
                   Registration at BrainMovers require user/s to share their personal details including but not limited to name, father's name, phone number, address, e-mail address, school and other academic information, which may be used by BrainMovers to arrive at a proper psychometric assessment. Although certain information are mandatory, some are not so and you can choose not to provide those.
                    </p>
                    
                </ul>
              </div>
               <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>Automatic Information  </strong> </li>
                    <p>  
                  We receive and store certain types of information whenever you interact with us, as part of standard operation of the site. These include, but not limited to your browser type, operating system, IP address, date and time you visit the site, the areas or pages of the site that you visit, the amount of time you spend viewing the site, the number of times you return to the site, your location and other click-stream data and plural form of the terms. Whenever the context may require, any pronoun shall include both the corresponding masculine and feminine form. The terms as defined herein shall also read as such in the Privacy Policy as well as the Disclaimer of the Website.
                    </p>
                    
                </ul>
              </div>

              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>About Cookies  </strong> </li>
                    <p>  
                  We use cookies to collect the non-personal information described above. Cookies are unique identifiers that we transfer to your device and are stored in the hard drive of your computer which will enable our systems to recognize your device and provide you certain features. You are free to decline cookies. But by doing so, you may not be able to use certain features on the site or take full advantage of all of our offerings. 
                    </p>
                    
                </ul>
              </div>
              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>Access to BrainMovers through my Facebook/Google and other Social Media accounts.  </strong> </li>
                    <p>  
                  BrainMovers also provides access to you through your respective Google/Facebook accounts; or as the case may be, during which process your personal or any other information may be shared with BrainMovers, which may be used by BrainMovers in terms of the Privacy Policy. Further, irrespective of the mode of your login to the Website you shall remain bound by EULA/Privacy Policy and disclaimer of BrainMovers.
                    </p>
                    
                </ul>
              </div>

              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>Use of the information so collected</strong> </li>
                    <p>  
                  BrainMovers shall have the right to use your information you provided us and such usage of your information by us does not amount to violation of any rights you might have in your information. <br>
                  We may collect and use your information to
                  <div style="padding-left: 20px">
                      • Fulfill your request for products and services.<br>
                      • Provide you with targeted offers, site content and advertising on the website.<br>
                      • Contact you with information and promotional materials and offers from our company as well as from our affiliates, other related companies, educational institutions, marketing partners and other third parties. <br>
                      • BrainMovers may share the information provided by you with mentors. With government if required under law or by any other mode as permissible in law.<br>
                      • BrainMovers does not sell or rent your personal information to third party for their marketing purposes without your explicit consent and we only use your information as described in the Privacy Policy. We view protection of user’s privacy as a very important community principle. We understand clearly that your Personal Information and that of user is one of our most important assets.

                  </div>
                    </p>
                    
                </ul>
              </div>
              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>How Secure Is Information About Me?</strong> </li>
                    <p>  
                 The security of personal information you have provided to BrainMovers is of paramount importance to BrainMovers. When you enter sensitive information, such as login credentials and payment regarding information, we encrypt the transmission of that information using secure socket layer technology (SSL).
                    </p>
                    <p>BrainMovers follow generally accepted standards to protect the personal information submitted to us, both during transmission and once we receive it. However, no method of transmission over the Internet, or method of electronic storage, is 100% secure. Therefore, BrainMovers cannot guarantee its absolute security.</p>
                    
                </ul>
              </div>
              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>Regarding changes in the privacy policy</strong> </li>
                    <p>  
                 BrainMovers Privacy Policy may change from time to time. BrainMovers will not reduce your rights under this Privacy Policy without your explicit consent. BrainMovers will post any privacy policy changes on this page and, if the changes are significant, BrainMovers will provide a more prominent notice (including, for certain services, email notification of privacy policy changes). BrainMovers will also keep prior versions of this Privacy Policy in an archive for your review.
                    </p>
                    
                </ul>
              </div>
              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>Acceptance</strong> </li>
                    <p>  
                 By using the Site and/ or by providing your Information you consent to the collection and use of the information you disclose on the Site by <b>BrainMovers</b> in accordance with <b>BrainMovers</b> Privacy Policy. You agree and acknowledge that you have read and fully understood the Privacy Policy and the terms and contents of such Privacy Policy as mentioned in the Website is acceptable to you.
                    </p>
                    
                </ul>
              </div>
            </div>
            
             
          </div>
        </div>
        
    
        
      </div>
    </div>
   </section>
    <!--End Page Title-->
  
  <!-- Case Section Three-->
   
  <!-- End Case Section Three-->
  
  <!-- Call To Action Two -->
  <section class="call-to-action-two">
    <div class="auto-container">
      <div class="clearfix">
        
        <div class="pull-left">
          <h2>Request for <span>Guidance</span></h2>
        </div>
        <div class="pull-right">
          <a href="{{URL('contact')}}" class="theme-btn btn-style-five">Request now <span class="icon fa fa-arrow-right"></span></a>
        </div>
        
      </div>
    </div>
  </section>
  <!-- End Feature Section -->
@endsection
