@extends('layouts.app')

@section('content')

    
  <!--Page Title-->
    <section style="padding: 179px 0px 90px;background-image:url({{asset('assets/images/background/8.jpg')}} )" class="page-title" >
      <div class="auto-container">
      <div class="content">
        <h1>Terms and <span>Conditions</span></h1>
        <ul class="page-breadcrumb">
          <li><a href="./">Home</a></li>
          <li>Pages</li>
          <li>Terms and Conditions</li>
        </ul>
      </div>
        </div>
    </section>
    <!--End Page Title-->
  
 <section class="about-section">
    <div class="auto-container">
      <div class="row clearfix">
        
        <!-- Content Column -->
        <div class="content-column col-lg-12 col-md-12 col-sm-12">
          <div class="inner-column">
            
            <!-- Sec Title -->
            <div class="sec-title">
              <div class="title">Terms and conditions</div>
              
            </div>
            
           
            <div class="row clearfix">
              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>INTRODUCTION</strong></li>
                                    <p>  
This document is an electronic record in terms of Information Technology Act, 2000 and Rules made there under as applicable. This electronic record is generated by a computer system and does not require any physical or digital signatures. 
</p>


<p>  
This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and user agreement of access or usage of a website. Here website means www.brainmovers.com.
</p>
<p>  
www.brainmovers.com., is a technology enabled multi dimensional career assessment website that helps the users in career planning in the best of their interests. Before using our services/ products you should go through the present Agreement (herein after referred to as EULA) and agree to the terms and conditions of the EULA. The User of the site shall be deemed to have read the terms of the EULA and duly accepted them before browsing through the website.
</p>
<p>  
These terms may be changed / updated from time to time solely at our discretion. By using our site you will be bound by the terms and conditions as mentioned in the EULA. You are required to and responsible for regularly reviewing the EULA to keep yourself updated with the changes/ amendments to the EULA as made by us from time to time. If u continue to access the website subsequent to such changes to EULA, you will be deemed to have accepted and agreed to the said changes.
</p>
                </ul>
              </div>
              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>REFERENCE OF TERMS USED IN EULA</strong></li>
                                    
                                    <p>    
 The terms used in the present EULA have been defined hereunder:</p>
<p> The term ‘BrainMovers” is used through this entire EULA to refer to the Website, its owner, directors, employees, and individuals / entities associated with the Owner.</p>
<p> The term ‘USER or YOU or YOUR’ is used through this entire EULA to refer to the any person who access the website or who is/are registered at the website for various services provided by it (User would include individual/legal entity/society/group of people etc. or as the case may be).</p>
<p> The term ‘OUR WEBSITE‘ or ‘WEBSITE’ is used through this entire EULA to refer to the Website www.brainmovers.com.</p>
<p> The term ‘OUR PRODUCTS /SERVICES’ is used through this entire EULA to refer to the products/ services offered at the Website or its associated entities, not including the advertisements that may be displayed on the Website.</p>
<p> The term ‘APPROPRIATE GOVERNMENT’ is used through this entire EULA as referring to Central/State Government or Local authorities as the case may be.
The terms and conditions herein shall apply equally to both the singular and plural form of the terms. Whenever the context may require, any pronoun shall include both the corresponding masculine and feminine form. The terms as defined herein shall also read as such in the Privacy Policy as well as the Disclaimer of the Website.
  
</p>
                </ul>
              </div>
              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>ELIGIBILITY</strong></li>
                                    <p>  
 Use of the Website is available to all the persons/entities/companies/partnership firms etc., as the case may be. However, any registration on the website shall be by the person who is capable of entering into valid contract as per the Indian Contract Act, 1872.</p>
<p>Persons who are “incompetent to contract” within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Website, except under the legal/constructive guardianship of such persons capable of entering into contract on behalf of such minor user/s.</p>
<p>
While registering with the Website, you represent that the information filled by you is correct and that you are duly authorized to accept this agreement and you have the authority to bind yourself / your business entity to this agreement.You further confirm that you shall use/browse the Website in terms of the EULA.</p>
<p>
You need not register with BrainMovers to simply visit and view the Platform, but to access and participate in certain features of the Platform, you will need to create a password- protected account (“Account”). To create an account, you must submit your name and email address through the account registration page on the Platform and create a password. You will also have the ability to provide additional optional information, which is not required to register for an account but may be helpful to BrainMovers in providing you with a more customized experience when using the Platform. You may also register for an Account using your other existing account and log-in credentials (your “Third-Party Site Password”).</p>
<p>BrainMovers reserves the right to terminate your registration and refuse to provide you with access to the Website if it is brought to our notice or if it is discovered that you are using the site in violation of the EULA or at its sole discretion without any reason thereof.
 
</p>
                </ul>
              </div>
          

          <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>OBLIGATION OF REGISTRATION</strong></li>
                                    <p>  
 You are responsible for maintaining the confidentiality of your User ID and Password. You are responsible for all the activities that occur under your User ID and Password. You agree, inter-alia, to;</p>
<p>Provide true, accurate, current and complete information about yourself as prompted by BrainMovers registration form (both personal and professional information), maintain and promptly update the Registration Data to keep it true, accurate, current, and complete at all times;
</p>
<p>
You must immediately notify us of any unauthorized use of your password or account or any other breach of security, and ensure that you exit from your account at the end of each session.
</p>
<p>
If you provide any information that is untrue, inaccurate, not current, or incomplete or BrainMovers has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with this Agreement, BrainMovers has the right to indefinitely suspend or terminate or block access of your registration with the website.</p>
<p>BrainMovers shall not be liable for any loss or damage arising from your failure to comply with this Clause.
 
</p>
                </ul>
              </div>


 <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>E- REGISTRATION AND COMMUNICATION</strong></li>
                                    <p>  
 When you use the Website or send emails or other data, information or communication to BrainMovers, you agree and understand that you are communicating with BrainMovers through electronic records. You consent to receive communications from us electronically. We will communicate with you by email or by posting notices on the Website or through any other BrainMovers services.</p>

                </ul>
              </div>

               <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>DESCRIPTION OF SERVICES</strong></li>
                                    <p>  
 BrainMovers is a technology enabled platform for career planning & development for students. BrainMovers offers a unique way of career guidance, counseling & mentoring and is not limited to psychometric assessments, counseling and guidance, interactive career focused activities etc., as may be provided time to time for help and guidance of user/s. thereby allowing them to take an informed decisions/choice at the right time.</p>
<p>By entering into the present agreement, you accept that you are using the services rendered at BrainMovers at your sole discretion without any undue influence of the BrainMovers and at your sole responsibility (under supervision of guardian in case of minors).
</p>
<p>
You further agree to ensure that you will ensure that you avail the services with due care and due diligence and as per the terms & conditions of the EULA and the respective service you are availing.
</p>

                </ul>
              </div>

                <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>PRICE</strong></li>
                                    <p>  
 BrainMovers shall charge a price for the services provided. By using the services which are subject to payment, you accept to pay for the same before using the services.</p>
<p>You further undertake not to raise any dispute qua the price charged for the services in any manner whatsoever as you have agreed to the same out of free will and without any undue influence.
</p>
<p>
The price to be charged by BrainMovers from users shall be decided solely by BrainMovers and the user/s shall have no right/say to interfere in the same.
</p>

                </ul>
              </div>

                <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>TAXES</strong></li>
                                    <p>  
 You agree to bear all applicable taxes, charges cess etc. levied on the services being rendered to you as notified by the Central/State Govt. time to time, unless already included in the price offered.</p>


                </ul>
              </div>
 <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>REFUND POLICY</strong></li>
                                    <p>  
 BrainMovers renders services including but not limited to counseling, assessment tests etc, which act as a bonafide guide to the user and the services are rendered as soon as availed, therefore there is no provision for refund of fee paid by the User/s. The user/s is therefore deemed to have understood and accepted that once the price is paid to the BrainMovers as per the services availed, there shall be no refund of the said Fee.
</p>


                </ul>
              </div>

               <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>TERM AND TERMINATION OF THE CONTRACT</strong></li>
                                    <p>  
There shall be no Contract between the BrainMovers and the user/s until the services are availed by user/s against consideration. The Access to the free portion of the website is only for welfare of the user and does not give rise to any Contract between the user/s and the BrainMovers in any manner.
</p>                                    
<p>  
The Contract against consideration for the services shall be strictly in terms of the services availed and shall end as soon as the services are rendered.
</p>                                  
  <p>  
BrainMovers is entitled to terminate the contract at all times and with immediate effect (by disabling your use of the Website and the Service) if you Violate or breach any term of this EULA, or In the opinion of BrainMovers, misuse the Website or Service, or At the sole discretion of the BrainMovers for which BrainMovers is under no obligation to assign any reason.
</p>
  <p>  
BrainMovers is not obliged to give prior notice of the termination of contract.
<br>
Dispute resolution<br>
The parties shall attempt that in the event of there being any dispute between them during the use of the website or thereafter, in connection with the validity, interpretation, implementation or alleged breach of any provision of the User Agreement, or the documents they incorporate by reference or anything relating to the present EULA, the dispute is settled by mutual discussion. In the event of failure of discussion, the dispute shall be referred to a sole Arbitrator, who shall be an independent and neutral third party appointed by BrainMovers. The place of arbitration shall be Bhopal, Madhya Pradesh, India. The Arbitration proceedings shall be in the English Language and shall be governed by Arbitration & Conciliation Act, 1996 as amended up to date.

</p>


                </ul>
              </div>

               <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>INTELLECTUAL PROPERTY OWNERSHIP</strong></li>
                                    <p>  
The data and information contained on the BrainMovers.in service , the software used to operate  it and the trade marks, logos and other intellectual property used in connection  with it are the property  of BrainMovers.in. No license of any such intellectual property rights in granted to you as a result of your use to the BrainMovers.in service. All the information on the website www.brainmovers.in like careers data, colleges data, assessment tests, assessment reports etc. are proprietary of BrainMovers.in and hence any infringement of copyright would be liable of civil action.
</p>  <p>  
You may not use, copy, adapt, modify, create derivative works from, distribute, license, sell, transfer, publicly display, publicly perform, reproduce, transmit, stream, broadcast or otherwise exploit the Website, Service or Collective Content, except as expressly permitted in this BrainMovers. You may not use any Collective Content without first obtaining the written consent of BrainMovers.
</p>


                </ul>
              </div>

               <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>INTELLECTUAL PROPERTY OWNERSHIP</strong></li>
                    <p>  
                    The data and information contained on the BrainMovers.in service , the software used to operate  it and the trade marks, logos and other intellectual property used in connection  with it are the property  of BrainMovers.in. No license of any such intellectual property rights in granted to you as a result of your use to the BrainMovers.in service. All the information on the website www.brainmovers.in like careers data, colleges data, assessment tests, assessment reports etc. are proprietary of BrainMovers.in and hence any infringement of copyright would be liable of civil action.
                    </p>  
                    <p>  
                    You may not use, copy, adapt, modify, create derivative works from, distribute, license, sell, transfer, publicly display, publicly perform, reproduce, transmit, stream, broadcast or otherwise exploit the Website, Service or Collective Content, except as expressly permitted in this BrainMovers. You may not use any Collective Content without first obtaining the written consent of BrainMovers.
                    </p>
                </ul>
              </div>
               <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>WEBSITE LICENSE</strong></li>
                    <p>  
                    Subject to your compliance with these EULA, BrainMovers grants you a limited non-exclusive, non-transferable license for the use of the Website.
                    </p>  
                    <p>  
                    You shall not indulge in any of the following activities:
                    </p>
                    <p>
                      
<b>1.</b> License, sub license, sell, resell, transfer , assign, distribute or otherwise commercially exploit or make available to any third party the Service or Website in any way.<br>
<b>2.</b> Modify or make derivative works based upon the Service or Website.<br>
<b>3.</b> Create internet “links” to the Service or “frame” or “mirror” any Website or any other server or wireless or Internet – based device.<br>
<b>4.</b> Reverse engineer or access the Website in order to Design or build a competitive product or service,
Design or build a product using similar ideas, features, functions, or graphics of the Service or Website’ or
Copy any ideas, features, functions or graphics of the Service or Website Launch an automated program or script, including, but not limited to, web spiders, web crawlers, web robots, web ants, we indexers, bots, viruses or worms or any program which may make multiple server requests per second, or unduly burdens or hinders the operation and/ or performance of the Website.<br>

<b>5.</b> Send spam or otherwise duplicative or unsolicited messages in violation of applicable laws.<br>

<b>6.</b> Send or store infringing, obscene, threatening, libelous, harassing, hateful, slanderous, threatening ,defamatory, racially, culturally or ethnically offensive, bigotry, vulgarity, profanity or otherwise unlawful or tortuous material, including material harmful to children or voilative of third party privacy rights.<br>

<b>7.</b> Send or store material containing software viruses, worms, Trojan horses or other harmful computer code, files, scripts, agents or programs.<br>

<b>8.</b> Interfere with or disrupt the integrity or the performance of the Website, the Website or Service or the data contained therein.<br>
<b>9.</b> Attempt to gain unauthorized access to the website.
<div style="padding-left: 10px;">
  <b>A.</b> Will not authorize others to use your account.<br>
  <b>B.</b> Will not assign or otherwise transfer your account to any other person or legal entity.<br>
 <b>C.</b> Will not use an account that is subject to any rights of a person other than you without appropriate authorization.<br>
  <b>D.</b> Will not use the Service or website for unlawful purposes, including but not limited to sending or storing any unlawful material or for fraudulent purposes.<br>
  <b>E.</b> Will provide us with whatever proof of identity we may reasonably request.<br>
  <b>F.</b> Will comply with all the applicable law from your home nation, the country, state and/ or city in which you are present while using the Website or the Service.
  </div>

<b>10.</b> BrainMovers will have the right to investigate and prosecute violations of any of the above to the fullest extent of the law. BrainMovers may involve and cooperate with law enforcement authorities in prosecuting users who violate these User Terms.<br>

<b>11.</b> You acknowledge that BrainMovers has no obligation to monitor your access to or use of the Website, Service or Collective Content or to review or edit any Collective Content, but has the right to do so for the purpose of operating the Website, to ensure your compliance with these User Terms or to comply with the applicable law or the order or requirement of a court, administrative agency or other governmental body.<br>

                    </p>
                </ul>
              </div>

               <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>CONDITIONS FOR USE OF WEBSITE</strong></li>
                    <p>  
                   In accordance with the Information Technology (Intermediaries guidelines) Rules 2011 and further guidelines as may be issued by the appropriate government time to time, in case of non compliance with rules and regulations, user agreement and privacy policy, for access or usage of intermediaries computer resources, the Intermediary has the right to immediately terminate the access or usage rights of the users to the computer resources of Intermediaries and remove non- complaint information.
                    </p>  
                    <p>  
                    In case if you post or transmit any content which BrainMovers believes is not in accordance with this EULA (including materials which infringe or may infringe third party intellectual property rights, rights of privacy or personality rights), or is otherwise unacceptable to BrainMovers.
                    </p>
                    <p>  
                    We reserve the right at our sole discretion to immediately terminate the access or usage rights of the users to our computer resources and block or remove(in whole or in part) the noncompliant information posted or transmitted by you.
                    </p>
                    <p>  
                    You warrant that the information you provide to BrainMovers is accurate and complete. We are entitled at all times to verify the information that you have provided us and to refuse the Service or use of the website, partially or completely, at our sole discretion, without providing any reasons, at any time.
                    </p>
                    <p>  
                    You may only access the Services using authorized means.
                    </p>
                     <p>  
                    In terms of Information Technology (Intermediaries guidelines) Rules 2011, you agree and undertake that you shall not host, display, upload, modify, publish, transmit, update or share any information or share/list(s) any information or item that belongs to the another person and to which You do not have any right is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another’s privacy, hateful or racially/ ethically objectionable, disparaging, relating or encouraging money laundering or gambling or otherwise unlawful in any manner whatsoever; or unlawfully threatening or unlawfully harassing including but not limited to “indecent representation of women” within the meaning of the Indecent Representation of Women ( Prohibition) Act,1986.Harm minors in any way, Infringes any patent, trademark, copyright or other proprietary rights or third party’s trade secrets or right of publicity or privacy or is fraudulent or involves the sale of counterfeit or stolen items Involves the transmission of “junk mails”, “chain letters”, or unsolicited mask mailing or “spamming”
                    </p> 
                    <p>  
                    Violates any law for the time being in force.
                    </p> 
                    <p>  
                    Deceives or misleads addressee/users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature.
                    </p> 
                    <p>  
                    Impersonate another person.
                    </p>
                    <p>Contains software viruses or any other computer code, file or programs designed to interrupt, destroy or limit the functionality of any computer resources.</p>
                    <p>Threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.</p>
                    <p>Is false, inaccurate or misleading.</p>
                    <p>You agree to promptly notify BrainMovers in writing of any user content which breaches these User Terms. You agree to provide us sufficient information to enable us to investigate whether such User Content breaches the terms of EULA. BrainMovers agrees to make good faith efforts to investigate such a complaint and shall take such notice as we in our sole discretion decide. However, BrainMovers does not warrant or represent that it will block or remove (in whole or in part) such user Content.</p>
                   
                </ul>
              </div>


               <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>CONSEQUENCES OF BREACH OF TERMS</strong></li>
                    <p>  
                    Without limiting other remedies that BrainMovers may pursue, we may at our sole discretion take such action as it deems fit including but not limited to limit your activity, immediately remove your information, warn other users of your actions, forthwith temporarily/indefinitely suspend or terminate or block your subscription, and/or refuse to provide you with access to the Website or initiate any legal action it may deem fit, particularly in the event.
                    </p>  
                    <p>  
                    You breach any of the provisions of this User Agreement including any of the rules and policies, documents, terms and conditions made there under which are incorporated therein by reference.
                    </p>
                    <p>  
                   Failure of verification or authentication of any information provided by you.
                    </p>
                    <p>  
                   If we believe that your actions may cause legal liability for you, other users or us.
                    </p>
                    <p>  
                    If you fail to immediately rectify such breach upon receiving written notice thereof from us.
                    </p><p>  
                   No actions, omissions or decisions taken by the Company shall waive any rights or claims that the Company may have against the user.
                    </p><p>  
                   We may at any time at our sole discretion reinstate suspended users.
                    </p><p>  
                    Any user that may have been suspended or blocked may not register or attempt to register with the Website or use the Website in any manner whatsoever until such time that such user is reinstated by the Company.
                    </p><p>  
                   Notwithstanding the above, if you breach the Agreement or the rules and policies and other documents incorporated therein by reference, BrainMovers reserves the right to forfeit the money paid by you to us and to take strict legal action including but not limited to referral to the appropriate police or other authorities for initiating criminal or civil or other proceedings against you.
                    </p>
                    <p>  
                    BrainMovers reserves its right to initiate civil and/or criminal proceedings against a user/s, who furnishes invalid/false claim or misleading information to BrainMovers.
                    </p> <p>  
                   Any person who, knowingly and with an intent to injure, defraud or deceive BrainMovers, files fraudulent information containing false, incomplete, or misleading information shall be guilty of a criminal offence and will be prosecuted to the fullest extent of the law.
                    </p>
                </ul>
              </div>

              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>DEFICIENCY IN SERVICE</strong></li>
                    <p>  
                   BrainMovers reserves the right to temporarily/ indefinitely suspend or terminate your registration and refuse to provide you with access to all current and future use of the Website at its sole discretion which shall not be termed as deficiency in service in any manner as per law and the user/s hereby expressly waives its right to call in question in any manner, any such suspension/termination of services by the BrainMovers.
                    </p>  
                    <p>  
                   BrainMovers reserves its right to suspend the operation of the website for updation/repair/technical fault or any other reason as the case may be for which it shall not be liable in any manner including for deficiency of service under the applicable laws.
                    </p>
                    <p>  
                       Force Majeure Events
                    </p>
                    <p>  
                   Any fault in or damage to Service Equipment or Network or components thereof for reasons beyond the reasonable control of the Company.
                    </p>
                    <p>  
                    Any complaint by the User which the Company, after due investigation, finds to be without any basis.
                    </p><p>  
                  Any order from the state or central government.
                    </p><p>  
                   BrainMovers reserves the right to temporarily/ indefinitely suspend or terminate your registration and refuse to provide you with access to all current and future use of the Website at its sole discretion which shall not be termed as deficiency in service in any manner as per law and the user/s hereby expressly waives its right to question in any manner, any such suspension/termination of services by BrainMovers.
                    </p>
                </ul>
              </div>

              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>INDEMNITY</strong></li>
                    <p>  
                  You confirm that you (alone) shall be responsible and will bear consequences and will defend, indemnify and hold us harmless from any losses, liabilities, damages, costs and expenses, claim or demand, or actions including reasonable attorneys’ fees asserted against or incurred by us, claims made by any third party, caused /arising out of or in connection with wrongful use of the website or its content by you including but not limited to Intellectual property Violations/Breach of terms & Conditions of EULA or in any manner as the case may be.
                    </p>  
                    <p>  
                   Your violation or breach of any term of these User Terms or any applicable law or regulation, whether or not referred herein.
                    </p>
                    <p>  
                       Your violation of any rights of any third party, including experts arranged via the Website, or Your use or misuse of the Website or Services.

                    </p>
                   
                </ul>
              </div>
               <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>LIABILITY</strong></li>
                    <p>  
                  The information, recommendations and/ or services provided to you on or through the Website, the Service and the Website is for general information purposes only as bonafide guidance and does not constitute any commitment of performance of user in any manner.
                    </p>  
                    <p>  
                  BrainMovers endeavors to provide the utmost quality of the services rendered and shall make every effort to keep the site and its contents correct and up to date. However, User agrees and acknowledges that we make no representations or warranties about the accuracy, reliability, completeness, and/or timeliness of any content, information, text, graphics, links or communications provided on or through the use of the Website or that the operation of the Website will be free of errors, defects, malware and viruses and/or uninterrupted.
                    </p>
                    <p>  
                       BrainMovers may permit advertisements of third parties on the website and shall not be responsible for the contents/assurances/services or anything relating to such third party advertisement in any manner whatsoever.

                    </p>
                   
                </ul>
              </div>
              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>LIMITATION OF LIABILITY</strong></li>
                    <p>  
                 BrainMovers will not be liable to you (whether under the law of contract, the law of torts or otherwise) in relation to the contents of, or use of, or otherwise in connection with, this website, for any direct, indirect, incidental, special, consequential or for any business losses, loss of revenue, income, profits or anticipated savings, loss of contracts or business relationships, loss of reputation or goodwill, or loss or corruption of information or data or other intangible losses arising out of or in connection with the website, its services or this agreement (however arising, including negligence).
                    </p>  
                    <p>  
                  BrainMovers assumes no liability whatsoever for any monetary or other damage suffered by you on account of:
                    </p>
                    <p>  
                      The delay, failure, interruption, or corruption of any data or other information transmitted in connection with use of the Website.

                    </p>
                    <p>  
                     Any interruption or errors in the operation of the Website.

                    </p>
                   
                </ul>
              </div>
              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>COMMUNICATION POLICY</strong></li>
                    <p>  
                You are prohibited to engage in direct or indirect communication with Counselors/consultants of BrainMovers except for the purposes of the services availed by you.
                    </p>  
                    <p>  
                 BrainMovers intermediate the communication between user/s and the Counselors which shall be limited for the purposes of service availed and the BrainMovers shall not be responsible for any communication between the user and the counselor beyond the scope of the services availed by the user/s in any manner whatsoever.
                    </p>
                    <p>  
                      Violations of policy may result in a range of actions including:
                      <div style="padding-left: 20px;">
                        <b>1.</b> Cancellation of your registration<br>
                        <b>2.</b> Limits on account privileges<br>
                        <b>3.</b> Account suspension<br>
                        <b>4.</b> Compensation for breach of duty<br>
                        <b>5.</b> Other proceedings as the law may prescribe<br>
                      </div>

                    </p>
                   
                </ul>
              </div>

              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>NOTICE</strong></li>
                    <p>  
                BrainMovers may give notice by means of a general notice on the Website, or by electronic mail to your e-mail address on record in BrainMover’s account information, or by written communication sent by regular mail to your address on record in BrainMover’s account information.
                    </p>  
                    <p>  
                 You agree that all the agreements, notices, disclosures and other communications that we provide to you electronically shall be deemed adequate service of notice/ electronic record and satisfy any legal requirement that such communication be in writing in terms of the present EULA.
                    </p>
                  
                   
                </ul>
              </div>

              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>FEEDBACK</strong></li>
                    <p>  
               BrainMovers is always open to the suggestions of the user/s and shall endeavor to doo all such suggestions that may enhance the utility to the user/s for the benefit of user/s as well as BrainMovers. However, BrainMovers is not bound by such suggestions in any manner whatsoever and incorporating such feedbacks is in our sole discretion.
                    </p>  
                   
                </ul>
              </div>

              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>DISPUTE RESOLUTION</strong></li>
                    <p>  
              The parties shall attempt that in the event of their being any dispute between them during your use of the Website or thereafter, in connection with the validity, interpretation, implementation or alleged breach of any provision of the User Agreement, or the documents they incorporate by reference or anything relating to the present EULA, the dispute is settled by mutual discussion. In the event of failure of discussion the dispute shall be referred to a sole Arbitrator, who shall be an independent and neutral third party appointed by BrainMovers . The place of arbitration shall be Bhopal, Madhya Pradesh India. The Arbitration proceedings shall be in the English Language and shall be governed by Arbitration & Conciliation Act, 1996.
                    </p>  
                   
                </ul>
              </div>

              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>SEVERABILITY</strong></li>
                    <p>  
              If any clause of this Agreement shall be deemed invalid, void or for any reason unenforceable, such clause shall be deemed severable and shall not affect the validity and enforceability of the remaining clauses of the Agreement.
                    </p>  
                   
                </ul>
              </div>

              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>JURISDICTION</strong></li>
                    <p>  
               For any dispute arising out of the present agreement only the Courts at Bhopal would Jurisdiction and the you undertake not to raise challenge to the jurisdiction clause in any manner and accept the jurisdiction of the Court at Bhopal.
                    </p>  
                   
                </ul>
              </div>

              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>LEGAL ADVICE</strong></li>
                    <p>  
               You undertake that you had every opportunity to take legal opinion on the present agreement and have understood the legal implications of every clause before agreeing to the same in totality and using the Website.
                    </p>  
                   
                </ul>
              </div>

              <div class="column col-lg-12 col-md-12 col-sm-12">
                <ul class="list-style-one">
                  <li><strong>ASSIGNMENT</strong></li>
                    <p>  
              No rights and obligations under this Agreement shall be assigned by Licensee whether voluntarily or involuntarily or by operation of law, in whole or in part, to any party without the prior written consent of BrainMovers, which may be granted or refused at our sole discretion. No such assignment by Licensee howsoever occurring shall relieve the Licensee of its obligations hereunder. Any assignment in violation of this clause shall be null and void from the beginning, and shall be deemed as a material breach of this Agreement.
                    </p>  

                    <p>
                      You cannot assign or otherwise transfer this agreement or any rights granted here under to any third party. BrainMovers may transfer its rights and obligations( also known as “ assign”) under this Agreement without your prior express consent, provided that BrainMovers assigns the Agreement on the same terms or terms that are no less advantageous to you
                    </p>
                   
                </ul>
              </div>

            
            </div>
            
             
          </div>
        </div>
        
       
        
      </div>
    </div>
   </section>
    <!--End Page Title-->
  
  <!-- Case Section Three-->
   
  <!-- End Case Section Three-->
  
  <!-- Call To Action Two -->
  <section class="call-to-action-two">
    <div class="auto-container">
      <div class="clearfix">
        
        <div class="pull-left">
          <h2>Request for <span>Guidance</span></h2>
        </div>
        <div class="pull-right">
          <a href="{{URL('contact')}}" class="theme-btn btn-style-five">Request now <span class="icon fa fa-arrow-right"></span></a>
        </div>
        
      </div>
    </div>
  </section>
  <!-- End Feature Section -->
@endsection
